apiVersion: v1
name: osdf-origin-public
# Chart version
version: 0.1
description: OSDF origin serving public data
# Version of application packaged for installation
appVersion: "v5.5.0-rc1"
#home: https://opensciencegrid.org/docs/data/stashcache/overview/
