apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
data:
  # The first public or auth origin export is declared in the environment;
  # the rest are in a config file.
  exports.cfg: |
    {{ if .Values.publicOrigin.enabled -}}
    if named stash-origin
    {{ range .Values.publicOrigin.exports }}
      all.export {{ . }}
    {{ end }}
    fi
    {{- end }}
    {{ if .Values.authOrigin.enabled -}}
    if named stash-origin-auth
    {{ range .Values.authOrigin.exports }}
      all.export {{ . }}
    {{ end }}
    fi
    {{- end }}

  {{ if .Values.publicOrigin.authfileLocal -}}
  stash-origin-Authfile.local: |
{{ .Values.publicOrigin.authfileLocal | indent 4 }}
  {{- end }}

  {{ if .Values.authOrigin.authfileLocal -}}
  stash-origin-auth-Authfile.local: |
{{ .Values.authOrigin.authfileLocal | indent 4 }}
  {{- end }}

  {{ if .Values.authOrigin.scitokensConfLocal -}}
  stash-origin-auth-scitokens.conf.local: |
{{ .Values.authOrigin.scitokensConfLocal | indent 4 }}
  {{- end }}

