apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
data:
  # The first public or auth origin export is declared in the environment;
  # the rest are in a config file.
  extra_exports.cfg: |-
    if named stash-origin
    {{ range (rest .Values.PublicOrigin.Exports) -}}
      all.export {{ . }}
    {{ end }}
    fi
    if named stash-origin-auth
    {{ range (rest .Values.AuthOrigin.Exports) -}}
      all.export {{ . }}
    {{ end }}
    fi
