apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
data:
  # The first public or auth origin export is declared in the environment;
  # the rest are in a config file.
  extra_exports.cfg: |
    {{ if rest .Values.publicOrigin.exports -}}
    if named stash-origin
    {{- range (rest .Values.publicOrigin.exports) -}}
      {{- printf "all.export %s" . | nindent 6 -}}
    {{ end }}
    fi
    {{- else -}}
    # No extra public exports given
    {{- end }}
    {{ if rest .Values.authOrigin.exports -}}
    if named stash-origin-auth
    {{- range (rest .Values.authOrigin.exports) -}}
      {{- printf "all.export %s" . | nindent 6 -}}
    {{ end }}
    fi
    {{- else -}}
    # No extra auth exports given
    {{- end }}

  {{ if .Values.extraConfigBefore -}}
  00-extra-before.cfg: |
{{ .Values.extraConfigBefore | indent 4 }}
  {{- end }}

  {{ if .Values.extraConfigAfter -}}
  99-extra-after.cfg: |
{{ .Values.extraConfigAfter | indent 4 }}
  {{- end }}

  {{ if .Values.publicOrigin.authfileLocal -}}
  stash-origin-Authfile.local: |
{{ .Values.publicOrigin.authfileLocal | indent 4 }}
  {{- end }}

  {{ if .Values.authOrigin.authfileLocal -}}
  stash-origin-auth-Authfile.local: |
{{ .Values.authOrigin.authfileLocal | indent 4 }}
  {{- end }}

  {{ if .Values.authOrigin.scitokensConfLocal -}}
  stash-origin-auth-scitokens.conf.local: |
{{ .Values.authOrigin.scitokensConfLocal | indent 4 }}
  {{- end }}

