apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
data:
  # The first public or auth origin export is declared in the environment;
  # the rest are in a config file.
  extra_exports.cfg: |
    {{ if rest .Values.PublicOrigin.Exports -}}
    if named stash-origin
    {{ range (rest .Values.PublicOrigin.Exports) -}}
      all.export {{ . }}
    {{ end }}
    fi
    {{- else -}}
    # No extra public exports given
    {{- end }}
    {{ if rest .Values.AuthOrigin.Exports -}}
    if named stash-origin-auth
    {{ range (rest .Values.AuthOrigin.Exports) -}}
      all.export {{ . }}
    {{ end }}
    fi
    {{- else -}}
    # No extra auth exports given
    {{- end }}

  {{ if .Values.PublicOrigin.AuthfileLocal -}}
  stash-origin-Authfile.local: |
{{ .Values.PublicOrigin.AuthfileLocal | indent 4 }}
  {{- end }}

  {{ if .Values.AuthOrigin.AuthfileLocal -}}
  stash-origin-auth-Authfile.local: |
{{ .Values.AuthOrigin.AuthfileLocal | indent 4 }}
  {{- end }}

  {{ if .Values.AuthOrigin.ScitokensConfLocal -}}
  stash-origin-auth-scitokens.conf.local: |
{{ .Values.AuthOrigin.ScitokensConfLocal | indent 4 }}
  {{- end }}

