apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "osdf-origin.name" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  template:
    metadata:
      labels:
        app: {{ template "osdf-origin.name" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}

    spec:
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.dataVolumes }}
      - name: {{ .name }}
        {{- if and (not (empty .claimName)) (not (empty .hostPath)) }}
          {{- fail "Specify claimName or hostPath, not both" -}}
        {{- else if .claimName }}
        persistentVolumeClaim:
          claimName: {{ .claimName }}
        {{- else if .hostPath }}
        hostPath:
          path: {{ .hostPath }}
          type: Directory
        {{- else }}
          {{- fail "Specify either claimName or hostPath" -}}
        {{- end }}
      {{- end }}

      {{- if .Values.hostCertKeySecret }}
      - name: hostcertkey
        secret:
          secretName: {{ .Values.hostCertKeySecret }}
          items:
          - key: tls.crt
            path: hostcert.pem
            mode: 0o644
          - key: tls.key
            path: hostkey.pem
            mode: 0o400
      {{- end }}
      - name: config
        configMap:
          name: {{ template "osdf-origin.fullname" . }}

      {{- if .Values.xrootdLogVolumeClaimName }}
      - name: xrootd-log
        persistentVolumeClaim:
          claimName: {{ .Values.xrootdLogVolumeClaimName }}
      {{- end }}

      # end volumes

      containers:
        - name: origin
          image: "{{ template "osdf-origin.origin-registry" . }}/{{ template "osdf-origin.origin-organization" . }}/stash-origin:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: XC_RESOURCENAME
            value: "{{ .Values.topologyResourceName }}"
          - name: ORIGIN_FQDN
            value: "{{ .Values.topologyFQDN }}"
          - name: XC_ROOTDIR
            value: "/xcache/namespace"
        {{- if .Values.publicOrigin.exports }}
          - name: XC_PUBLIC_ORIGIN_EXPORT
            value: "{{ first .Values.publicOrigin.exports }}"
        {{- end }}
        {{- if .Values.authOrigin.exports }}
          - name: XC_AUTH_ORIGIN_EXPORT
            value: "{{ first .Values.authOrigin.exports }}"
        {{- end }}

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbeEnabled }}
          livenessProbe:
            tcpSocket:
              {{- if .Values.authOrigin.enabled }}
              port: 1095
              {{- else if .Values.publicOrigin.enabled }}
              port: 1094
              {{- end }}
            initialDelaySeconds: 600
            periodSeconds: 60
          {{- end }}
          ports:
            {{- if .Values.authOrigin.enabled }}
            - containerPort: 1095
              hostPort: {{ default 1095 .Values.authOrigin.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.publicOrigin.enabled }}
            - containerPort: 1094
              hostPort: {{ default 1094 .Values.publicOrigin.port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            {{- range .Values.dataVolumes }}
            - mountPath: /xcache/namespace{{ .mountPath }}
              name: {{ .name }}
            {{ end }}
            {{- if .Values.hostCertKeySecret }}
            - mountPath: /etc/grid-security/hostcert.pem
              name: hostcertkey
              subPath: hostcert.pem
            - mountPath: /etc/grid-security/hostkey.pem
              name: hostcertkey
              subPath: hostkey.pem
            {{ end }}
            - mountPath: /etc/xrootd/config.d/extra_exports.cfg
              name: config
              subPath: extra_exports.cfg
            {{- if .Values.publicOrigin.authfileLocal }}
            - mountPath: /run/stash-origin/Authfile.local
              name: config
              subPath: stash-origin-Authfile.local
            {{ end }}
            {{- if .Values.authOrigin.authfileLocal }}
            - mountPath: /run/stash-origin-auth/Authfile.local
              name: config
              subPath: stash-origin-auth-Authfile.local
            {{ end }}
            {{- if .Values.authOrigin.scitokensConfLocal }}
            - mountPath: /run/stash-origin-auth/scitokens.conf.local
              name: config
              subPath: stash-origin-auth-scitokens.conf.local
            {{ end }}
            {{- if .Values.xrootdLogVolumeClaimName }}
            - mountPath: /var/log/xrootd
              name: xrootd-log
            {{ end }}
          # end volumeMounts
      # end containers
    # end spec
  # end template
# end spec

# vim:et:sw=2:sts=2:ts=8
