apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osdf-origin-public.fullname" . }}
  labels:
    app: {{ template "osdf-origin-public.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osdf-origin-public.name" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}

  template:
    metadata:
      labels:
        app: {{ template "osdf-origin-public.name" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}

    spec:
      volumes:
      - name: xcache-namespace
        persistentVolumeClaim:
          claimName: {{ .Values.Origin.DataVolume }}

      {{ if .Values.HostCredentials.HostCertKeySecret }}
      - name: hostcertkey
        secret:
          secretName: {{ .Values.HostCredentials.HostCertKeySecret }}
          items:
          - key: tls.crt
            path: hostcert.pem
            mode: 0o644
          - key: tls.key
            path: hostkey.pem
            mode: 0o400
      {{ end }}

      containers:
        - name: origin
          image: "{{ .Values.Containers.Origin.Image }}"
          imagePullPolicy: {{ .Values.Containers.Origin.ImagePullPolicy }}
          env:
          - name: XC_RESOURCENAME
            value: "{{ .Values.Topology.ResourceName }}"
          - name: ORIGIN_FQDN
            value: "{{ .Values.Topology.FQDN }}"
          - name: XC_ROOTDIR
            value: "/xcache/namespace"
          - name: XC_ORIGINEXPORT
            value: "{{ .Values.Origin.MainExport }}"

          resources:
            requests:
              cpu: "{{ .Values.Resources.CPU }}"
              memory: "{{ .Values.Resources.Memory }}"
            limits:
              cpu: "{{ .Values.Resources.CPU }}"
              memory: "{{ .Values.Resources.Memory }}"
          livenessProbe:
            tcpSocket:
              port: 1094
            initialDelaySeconds: 600
            periodSeconds: 60
          ports:
            - containerPort: 1094
              hostPort: 1094
              protocol: TCP
          volumeMounts:
            - mountPath: /xcache/namespace
              name: xcache-namespace
            {{ if .Values.HostCredentials.HostCertKeySecret }}
            - mountPath: /etc/grid-security/hostcert.pem
              name: hostcertkey
              subPath: tls.crt
            - mountPath: /etc/grid-security/hostkey.pem
              name: hostcertkey
              subPath: tls.key
            {{ end }}
